# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubrik-mcp" do
  name "rubrik-mcp"
  desc "Rubrik Security Cloud MCP Plugin — connect AI assistants to RSC"
  homepage "https://rubrikinc.github.io/rubrik-mcp"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubrik-mcp"

  on_macos do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_amd64.tar.gz"
      sha256 "7796d81373cc241dd0368b0ad701f76326a1be69d5b5361e18bf936f39943067"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_arm64.tar.gz"
      sha256 "11bbaab5f6315a19dfa811744437bdedb81986479e930bda3951395bfd9dd336"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_amd64.tar.gz"
      sha256 "bf1effa2ab4de5ea32451513ebe9930fb2232a0c43bda5238f404e4a0f332992"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_arm64.tar.gz"
      sha256 "69e9a5460b294da371bc9b4ab45bb2e75ce7482898e8c3e585d4e783997e2e6c"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rubrik-mcp"]
  end

  # No zap stanza required
end
