# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubrik-mcp" do
  name "rubrik-mcp"
  desc "Rubrik Security Cloud MCP Plugin — connect AI assistants to RSC"
  homepage "https://rubrikinc.github.io/rubrik-mcp"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubrik-mcp"

  on_macos do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_amd64.tar.gz"
      sha256 "085e20022244acc47a93eba1f5cc75e59a6a09cd205512cdf6b159c52b0b3408"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_arm64.tar.gz"
      sha256 "0f6e1a999c702cb16f44751b76f0533341d63137de11ce278e597a538bd1e959"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_amd64.tar.gz"
      sha256 "a56be7b564d631ad7ccfe228a4c0bc73bd923cec3f0c8c305816993373a64d5a"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_arm64.tar.gz"
      sha256 "b4132a72f3e2a154a114de8021bbb7d8de43cfee3c5cd4e6480efbb7d535728b"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rubrik-mcp"]
  end

  # No zap stanza required
end
