# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubrik-mcp" do
  name "rubrik-mcp"
  desc "Rubrik Security Cloud MCP Plugin — connect AI assistants to RSC"
  homepage "https://rubrikinc.github.io/rubrik-mcp"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubrik-mcp"

  on_macos do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_amd64.tar.gz"
      sha256 "e895cce7da57d1a884165c1be520fc47f3e2bb5ff0098d87c7115733613a0e21"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_arm64.tar.gz"
      sha256 "23a2144bde9292ffca1a733064edef93d1ed804ddf0c556285958d0872cd3439"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_amd64.tar.gz"
      sha256 "edffa0dcc1b3deaad2db079ad260d25aa3af4c54cb4976b56fea744969a4d84b"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_arm64.tar.gz"
      sha256 "09c3eb367b3de510953269151acfac0b7230b7e1d40d9886a2e757ab19e21cc5"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rubrik-mcp"]
  end

  # No zap stanza required
end
