# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubrik-mcp" do
  name "rubrik-mcp"
  desc "Rubrik Security Cloud MCP Plugin — connect AI assistants to RSC"
  homepage "https://rubrikinc.github.io/rubrik-mcp"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubrik-mcp"

  on_macos do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_amd64.tar.gz"
      sha256 "231ac501fe6dccd176b85327d9f5af31d56302b3b13f35dc80785368b6e612d9"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_darwin_arm64.tar.gz"
      sha256 "e84260670a8be41e47f6cce26baeee1d6a23b79c015d23d129f70cc43d23576d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_amd64.tar.gz"
      sha256 "06c712f4be55b2c2e2c8f2f8cadd38c2a131da36b42e65eb31a5a035328846a0"
    end
    on_arm do
      url "https://github.com/rubrikinc/rubrik-mcp/releases/download/v#{version}/rubrik-rsc-plugin_#{version}_linux_arm64.tar.gz"
      sha256 "23b64431be829fae77ad7a1b2eadc04f698e330f6cdd3714fd896089192ba6b0"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rubrik-mcp"]
  end

  # No zap stanza required
end
